on:
    pull_request:
        types: [opened, reopened]

jobs:
    move_to_in_review:
        runs-on: ubuntu-latest
        steps:
            - name: Move linked issue to In Review
              uses: nipe0324/update-project-v2-item-field@v2.0.2
              with:
                project-url: https://github.com/users/renancvitor/projects/2
                github-token: ${{ secrets.GH_TOKEN }}
                field-name: 'Status'
                field-value: 'In Review'