name: Set Type from Label
on:
  issues:
    types: [labeled]

jobs:
  set_type:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to renancvitor
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          assignees: renancvitor
      - name: Update Project v2 Type
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/renancvitor/projects/2
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: "Type"
          field-value: ${{ contains(toJson(github.event.issue.labels), 'feature') && 'Feature' || contains(toJson(github.event.issue.labels), 'bug') && 'Bug' || contains(toJson(github.event.issue.labels), 'refactor') && 'Refactor' || contains(toJson(github.event.issue.labels), 'tech-debt') && 'Tech Debt' || contains(toJson(github.event.issue.labels), 'docs') && 'Documentation' || contains(toJson(github.event.issue.labels), 'research') && 'Research' }}
